### ISSUE TITLE
[feature] error reporting line number

### ISSUE THREAD

**Issue by pjm-tusimple** [wireviz/WireViz#297]
is it possible for the errors to throw a line in the yaml file?  Knowing where the exception was thrown will help a lot.

**Comment by kvid** [comment]
As far as I know, pyyaml does not support line numbers out of the box, but it might be possible [via subclassing](https://stackoverflow.com/questions/13319067/parsing-yaml-return-with-line-number). However, an easier approach, is to specify node name and other context to locate the root cause, similar to suggestions in #207.

**Comment by pjm-tusimple** [comment]
> As far as I know, pyyaml does not support line numbers out of the box, but it might be possible [via subclassing](https://stackoverflow.com/questions/13319067/parsing-yaml-return-with-line-number). However, an easier approach, is to specify node name and other context to locate the root cause, similar to suggestions in #207.

Yes, it does look similar.  Thanks for pointing that out.
